import Head from 'next/head'
import { Container } from 'react-bootstrap'
import { MoviesTable } from '../components'
import axios from 'axios'

export async function getStaticProps() {
	try {
		const { data } = await axios.get(`${process.env.APP_DOMAIN}/api/movies/0`)

		console.log(data)

		return {
			props: {
				...data
			},
		}
	} catch (error) {
		console.error(error)
	}

	return {
		props: {
			length: 0,
			movies: []
		},
	}
}

export default function Home({ movies }) {
	return (
		<div>
			<Head>
				<title>S3 project - Movie list</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container style={{ marginTop: '50px' }}>
				<h1>Welcome to my movie list !</h1>
				<MoviesTable data={movies} />
			</Container>
		</div>
	)
}
