import Head from 'next/head'
import { makeQuery } from '../db'

export async function getStaticProps() {
  try {
    const data = await makeQuery('SELECT * FROM film')
    console.log(data)
    return {
      props: {
        movies: data
      },
    }
  } catch (error) {
    console.error(error)
  }

  return {
    props: {
      movies: []
    },
  }
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>S3 project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to my movie list !
        </h1>
      </main>
    </div>
  )
}
